### ISSUE TITLE
I think I need a way to get screenshots on failure?

### ISSUE THREAD

**Issue by NullVoxPopuli** [CrowdStrike/faltest#275] opened 2020-04-12 16:17 UTC
https://github.com/NullVoxPopuli/emberclear/pull/728/checks?check_run_id=580846382

Running in to the above ^ where I think the element isn't found, but I don't know why.

Locally, I can't anything to happen -- potentially because execa doesn't work on windows. (execa is what I'm using to launch a fake server from built assets)

**Comment by kellyselden** [comment] 2020-04-12 16:48
We should do this. You could start by looking at webdriver.io docs for how we would do this.

**Comment by kellyselden** [comment] 2020-04-12 16:49
Duplicate of #15

**Closed by kellyselden** 2020-04-12 16:49 UTC
